spring.application.name=chat

spring.datasource.url=jdbc:h2:file:./data/chat
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.security.user.name=admin
spring.security.user.password=123456

usuario.fulano.nome=Fulano
usuario.fulano.email=fulano@gmail.com
usuario.fulano.senha=123456

usuario.ciclano.nome=Ciclano
usuario.ciclano.email=ciclano@gmail.com
usuario.ciclano.senha=123456

usuario.beltrano.nome=Beltrano
usuario.beltrano.email=beltrano@gmail.com
usuario.beltrano.senha=123456